post_install() {
  printf "$nimrod\n"
}

post_upgrade() {
  post_install
}

read -d '' nimrod <<'EOF'
# vim-nimrod-git
Next you need to add this to your ~/.vimrc:

fun! JumpToDef()
  if exists("*GotoDefinition_" . &filetype)
    call GotoDefinition_{&filetype}()
  else
    exe "norm! \<C-]>"
  endif
endf

" Jump to tag
nn <M-g> :call JumpToDef()<cr>
ino <M-g> <esc>:call JumpToDef()<cr>i

The JumpToDef function hooks the nimrod.vim plugin to invoke the nimrod
compiler with the appropriate idetools command. Pressing meta+g will
then jump to the definition of the word your cursor is on. This uses the
nimrod compiler instead of ctags, so it works on any nimrod file which
is compilable without requiring you to maintain a database file.
EOF
