post_install() {
  printf "$cljsql\n"
}

post_upgrade() {
  post_install
}

read -d '' cljsql <<'EOF'
# vim-clojure-sql-git

## Usage

Whenever you edit a Clojure file, strings starting with "SELECT, "INSERT,
"UPDATE, "DELETE, "CREATE or "DROP will be highlighted as SQL.

Matches are case-sensitive, because that's my preference, but it's
trivial to fork & change the matching rules to suit your coding style.
EOF
