post_install() {
  printf "$tabular\n"
}

post_upgrade() {
  post_install
}

read -d '' tabular <<'EOF'
#|#|#|#|#|          #|                  #|                     ~
    #|      #|#|#|  #|#|#|    #|    #|  #|    #|#|#|  #|  #|#| ~
    #|    #|    #|  #|    #|  #|    #|  #|  #|    #|  #|#|     ~
    #|    #|    #|  #|    #|  #|    #|  #|  #|    #|  #|       ~
    #|      #|#|#|  #|#|#|      #|#|#|  #|    #|#|#|  #|       ~
EOF
