_gitname=nimrod.vim

post_install() {
  printf "$nim\n"
}

post_upgrade() {
  post_install
}

post_remove() {
  echo -n "Removing $_gitname directory... "
  rm -rf "$HOME/.vim/plugged/$_gitname"
  echo "done"
}

read -d '' nim <<'EOF'
# vim-nim-git
Next you need to add this to your ~/.vimrc:

fun! JumpToDef()
  if exists("*GotoDefinition_" . &filetype)
    call GotoDefinition_{&filetype}()
  else
    exe "norm! \<C-]>"
  endif
endf

" Jump to tag
nn <M-g> :call JumpToDef()<cr>
ino <M-g> <esc>:call JumpToDef()<cr>i

The JumpToDef function hooks the nimrod.vim plugin to invoke the nim
compiler with the appropriate idetools command. Pressing meta+g will
then jump to the definition of the word your cursor is on. This uses
the nim compiler instead of ctags, so it works on any nim file which is
compilable without requiring you to maintain a database file.
EOF
