_gitname=Liquid-Carbon

pre_install() {
  post_remove
}

post_install() {
  printf "%b\n" "$liquidcarbon"
}

pre_upgrade() {
  post_remove
}

post_upgrade() {
  post_install
}

post_remove() {
  echo -n "Removing $_gitname directory... "
  rm -rf "$HOME/.vim/plugged/$_gitname"
  echo "done"
}

read -d '' liquidcarbon <<'EOF'
For higher-contrast liquidcarbon colors (darker background):

    let g:liquidcarbon_high_contrast = 1
EOF
