_gitname=iceberg.vim

post_install() {
  printf "$iceberg\n"
}

post_upgrade() {
  post_install
}

post_remove() {
  echo -n "Removing $_gitname directory... "
  rm -rf "$HOME/.vim/plugged/$_gitname"
  echo "done"
}

read -d '' iceberg <<'EOF'
#  _________________________________________
#  \_ _/ ____| ____| ___ \ ____| ___ \ ___/
#  | | |____| ____| ___ < ____| __ / |__ \
#  /___\_____|_____|_____/_____|_| \_\_____/
#
#  cool-headed perspective for your coding
EOF
