_gitname=vimerl

post_install() {
  printf "$vimerl\n"
}

post_upgrade() {
  post_install
}

post_remove() {
  echo -n "Removing $_gitname directory... "
  rm -rf "$HOME/.vim/plugged/$_gitname"
  echo "done"
}

read -d '' vimerl <<'EOF'
   _    ___                     __
  | |  / (_)___ ___  ___  _____/ /
  | | / / / __ `__ \/ _ \/ ___/ /
  | |/ / / / / / / /  __/ /  / /
  |___/_/_/ /_/ /_/\___/_/  /_/
====================================

The Erlang plugin for Vim.
EOF
